# Quick test pipeline to validate git push permissions
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  - bash: |
      set -e
      echo "Testing git push permissions..."

      # Show identity info
      echo "Current git config:"
      git config --list | grep -E "user|url|credential" || true

      # Try to create and push a test tag
      TEST_TAG="test-permissions-$(date +%s)"
      echo "Creating test tag: $TEST_TAG"

      git config user.email "azure-pipelines@devpossible.com"
      git config user.name "Azure Pipelines"

      git tag -a "$TEST_TAG" -m "Test tag for permission validation"

      echo "Pushing test tag..."
      git push origin "$TEST_TAG"

      echo "SUCCESS: Git push permissions are working!"

      # Clean up - delete the test tag
      git push origin --delete "$TEST_TAG" || true
      git tag -d "$TEST_TAG" || true
    displayName: Test Git Push Permissions
